
services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - wordpress_data:/var/www/html/wordpress
    networks:
      - network

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - network


volumes:
  mariadb_data:
  wordpress_data:

networks:
  network:
    driver: bridge
