
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    restart: unless-stopped

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "8443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: unless-stopped

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: ~/data/mariadb
      o: bind
      type: none
  
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: ~data/wordpress
      o: bind
      type: none
  
networks:
  inception:
    name: inception