
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    expose:
      - "3306"
    networks:
      - inception_network
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    secrets:
      - db_pw
      - db_root_pw

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    expose:
      - "9000"
    depends_on:
      - mariadb
    networks:
      - inception_network
    volumes:
      - wordpress:/var/www/html/wordpress
    restart: unless-stopped
    secrets:
      - db_pw
      - wp_admin_pw
      - wp_user_pw

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
      - "8080:8080"
    depends_on:
      - wordpress
      - adminer
    volumes:
      - wordpress:/var/www/html/wordpress
      - static:/var/www/html/static
    networks:
      - inception_network
    restart: unless-stopped

  adminer:
    container_name: adminer
    build: ./requirements/adminer
    ports:
      - "8484:8484"
    networks:
      - inception_network
    restart: unless-stopped

secrets:
  db_pw:
    file: ./secrets/db_pw.txt
  db_root_pw:
    file: ./secrets/db_root_pw.txt
  wp_admin_pw:
    file: ./secrets/wp_admin_pw.txt
  wp_user_pw:
    file: ./secrets/wp_user_pw.txt

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: ~/data/mariadb
      o: bind
      type: none

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: ~/data/wordpress
      o: bind
      type: none

  static:
    name: static
    driver: local
    driver_opts:
      device: ~/data/static
      o: bind
      type: none

networks:
  inception_network:
    name: inception_network
    driver: bridge
